apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stalwart.fullname" . }}
  labels:
    {{- include "stalwart.labels" . | nindent 4 }}
data:
  config.toml: |
    [lookup.default]
    hostname = "mail.{{ .Values.mail.domain }}"

    [server.listener."http"]
    bind = ["0.0.0.0:80"]
    protocol = "http"

    [server.listener."smtp"]
    bind = ["0.0.0.0:25"]
    protocol = "smtp"

    [server.listener."submissions"]
    bind = ["0.0.0.0:465"]
    protocol = "smtp"
    tls.implicit = true

    [server.listener."imaptls"]
    bind = ["0.0.0.0:993"]
    protocol = "imap"
    tls.implicit = true

    [storage]
    data = "rocksdb"
    fts = "rocksdb"
    blob = "rocksdb"
    lookup = "rocksdb"
    directory = "internal"

    [store."rocksdb"]
    type = "rocksdb"
    path = "/opt/stalwart-mail/data"
    compression = "lz4"

    [directory."internal"]
    type = "internal"
    store = "rocksdb"

    [tracer."stdout"]
    type = "stdout"
    level = "info"
    ansi = false
    enable = true

    [authentication.fallback-admin]
    user = "%{env:ADMIN_USER}%"
    secret = "%{env:ADMIN_HASH}%"
