apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stalwart.fullname" . }}
  labels:
    {{- include "stalwart.labels" . | nindent 4 }}
type: Opaque
data:
  user: {{ .Values.fallbackAdmin.user | b64enc }}
  hash: {{ .Values.fallbackAdmin.hash | b64enc }}
