apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stalwart.fullname" . }}
  labels:
    {{- include "stalwart.labels" . | nindent 4 }}
type: Opaque
stringData:
  user: {{ .Values.fallbackAdmin.user | quote }}
  hash: {{ .Values.fallbackAdmin.hash | quote }}
