apiVersion: v1
kind: Service
metadata:
  name: {{ include "stalwart.fullname" . }}
  labels:
    {{- include "stalwart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  ports:
    - port: 25
      targetPort: 25
      protocol: TCP
      name: smtp
    - port: 465
      targetPort: 465
      protocol: TCP
      name: smtps
    - port: 993
      targetPort: 993
      protocol: TCP
      name: imaps
  selector:
    {{- include "stalwart.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stalwart.fullname" . }}-web
  labels:
    {{- include "stalwart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "stalwart.selectorLabels" . | nindent 4 }}
